name: mydevteam
description: Développement d'une application de gestion de projet tout-en-un .

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  #--UI
  cupertino_icons: ^1.0.2
  rounded_loading_button: ^2.1.0
  flutter_svg: ^2.0.9
  transparent_image: ^2.0.1
  clean_calendar: ^1.1.0
  table_calendar: ^3.0.6
  syncfusion_flutter_calendar : 
  scrollable_table_view: ^2.0.3
  ionicons: ^0.2.2
  appflowy_board: ^0.1.1
  window_manager: ^0.3.8
  flutter_expandable_table: ^2.0.1

  #--State managment
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc: ^8.1.2
  dartz: ^0.10.1
  get_it: ^7.6.0
  provider: ^6.0.5
  path: ^1.8.3
  path_provider: ^2.1.1

  #--Local Data
  shared_preferences: ^2.2.0
  objectbox: ^2.3.1
  objectbox_flutter_libs: any
  cached_network_image: ^3.3.0
  internet_connection_checker_plus: ^2.0.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  flutter_launcher_icons: ^0.13.1
  photo_gallery: ^2.1.1
  image_picker: ^1.0.7


  #--App
  auto_route: ^7.8.4
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2+1
  jwt_decoder: ^2.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  device_preview: ^1.1.0
  pinput: ^3.0.1
  country_code_picker: ^3.0.0
  intl_phone_number_field: ^0.1.8
  pocketbase: ^0.17.0
  url_launcher: ^6.2.3
  http: ^1.2.0
  device_info_plus: ^9.1.1
  mime: ^1.0.4
  http_parser: ^4.0.2
  flutter_osm_plugin: ^0.70.4
  pointer_interceptor: ^0.10.1
  flutter_typeahead: ^5.0.2
  calendar_view: ^1.1.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  objectbox_generator: any
  auto_route_generator: ^7.3.2
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/icons/
